title: Preethi's first blog
author: Preethi Ganeshan
email: iyerpreethi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site talks about interesting coding concepts and projects for beginners
# social links

github_username:  preethiganeshan-dev # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
